[package]
edition = "2021"
name = "ai_forward"
version = "0.1.0"

[dependencies]
colored = "3.0.0"
once_cell = "1.20.2"
rand = "0.9.0"
reqwest = {version = "0.12.12", features = ["json", "rustls-tls", "stream", "http2"], default-features = false}
salvo = {version = "0.76.1"}
serde = "1.0.217"
serde_json = "1.0.138"
tokio = {version = "1.43.0"}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
